### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by eliasah** [awesome-spark/awesome-spark#10]
Should we add some tutorials links ? What do you think ?

**Comment by zero323** [comment]
I am not convinced. In general I think it is better to focus on more comprehensive resources.

**Comment by eliasah** [comment]
I agree with you on that. But I was thinking of that maybe as a side project. Creating eventually the Spark Learning Hub. I might be early for that now, but eventually wouldn't it be a good idea ?

**Comment by zero323** [comment]
If you feel like this is a good idea and want to maintain it i trust your judgment. We can create a separate repository for that.

**Comment by eliasah** [comment]
I also think that we should create a separate repository fo tutorials as well. Thus I'm closing this issue for now.
