### ISSUE TITLE
Consider Flintrock

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#100]
https://github.com/nchammas/flintrock

We should probably wait until 1.0, but I'll leave to you @eliasah. Not like I am big AWS user :)

**Comment by eliasah** [comment]
This is still pending. We will wait.

**Comment by nchammas** [comment]
The spark-ec2 maintainer recently [announced](https://github.com/amplab/spark-ec2#readme) that the project is no longer under active development and that Flintrock is the recommended alternative.

Even though Flintrock is still not 1.0, perhaps this announcement means the project is worth considering for inclusion here.

**Comment by zero323** [comment]
@nchammas Sounds good. Could you create a PR? TIA
