### ISSUE TITLE
The licence badge has to be in SVG not PNG

### ISSUE THREAD

**Issue by eliasah** [awesome-spark/awesome-spark#119]
To be able to make this https://github.com/sindresorhus/awesome/pull/895 accept we need to change the badge format to SVG.

How are we supposed to make a svg of the licence batch if it's a link ? https://github.com/awesome-spark/awesome-spark/blob/master/README.md#license

**Comment by zero323** [comment]
<p xmlns:dct="http://purl.org/dc/terms/">
<a rel="license" href="http://creativecommons.org/publicdomain/mark/1.0/">
<img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/publicdomain.svg"
     style="border-style: none;" alt="Public Domain Mark" />
</a>
<br />
This work (<span property="dct:title">Awesome Spark</span>, by <a href="https://github.com/awesome-spark/awesome-spark" rel="dct:creator">https://github.com/awesome-spark/awesome-spark</a>), identified by <a href="https://github.com/zero323" rel="dct:publisher"><span property="dct:title">Maciej Szymkiewicz</span></a>, is free of known copyright restrictions.
</p>

Apache Spark, Spark, Apache, and the Spark logo are <a href="https://www.apache.org/foundation/marks/">trademarks</a> of
  <a href="http://www.apache.org">The Apache Software Foundation</a>. This compilation is not endorsed by The Apache Software Foundation.
