### ISSUE TITLE
Consider Big Data for Data Engineers Specialization

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#154]
https://www.coursera.org/specializations/big-data-engineering

> In four concise courses you will learn the basics of Hadoop, MapReduce, Spark, methods of offline data processing for warehousing, real-time data processing and large-scale machine learning. And Capstone project for you to build and deploy your own Big Data Service (make your portfolio even more competitive).

**Comment by eliasah** [comment]
I don't know. There is too many of them now. (lots of them are paid)
