### ISSUE TITLE
Consider Kyuubi

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#158]
https://github.com/yaooqinn/kyuubi

> Kyuubi is an enhanced edition of the Apache Spark's primordial Thrift JDBC/ODBC Server. It is mainly designed for directly running SQL towards a cluster with all components including HDFS, YARN, Hive MetaStore, and itself secured. Kyuubi is a Spark SQL thrift service with end-to-end multi tenant guaranteed. Please go to Kyuubi Architecture to learn more if you are interested.

CC @yaooqinn

**Comment by yaooqinn** [comment]
Thanks for considering
