### ISSUE TITLE
Include Spark logo

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#17]
It has not much practical value but it could look nice.

**Comment by eliasah** [comment]
It would look nice. But I was just worried about trademarks. But it seems to be resolved with #16

**Comment by zero323** [comment]
From the trademark guide:

_You needn't ask us for permission to use Apache's graphics logos (the versions published on individual project's websites) on your own website solely as a hyperlink to the specific Apache project website or to www.apache.org. All other uses of Apache Foo (and similar) graphic logos must be approved in writing by VP, Apache Brand Management, member of the Brand Management Committee, or the relevant Apache projects' VP._
