### ISSUE TITLE
Consider yaooqinn / itachi

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#194]
> itachi brings useful functions from modern database management systems to Apache Spark :)
>
> For example, you can import the Postgres extensions and write Spark code that looks just like Postgres.
>
> The functions are implemented as native Spark functions, so they're performant.

https://github.com/yaooqinn/itachi/

CC @yaooqinn @MrPowers

**Comment by yaooqinn** [comment]
lgtm，thanks very much

**Comment by zero323** [comment]
If you want to open PR for this @yaooqinn, I'll be happy to add it to a list, unless @eliasah or @oluies strongly oppose.
