### ISSUE TITLE
Conisder spark-daria

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#197]
https://github.com/mrpowers/spark-daria

>  Spark helper methods to maximize developer productivity.

Just because Daria, duh....

**Comment by zero323** [comment]
cc @MrPowers

**Comment by MrPowers** [comment]
Let me know if this is cool and I'll be happy to submit a PR ;)

**Comment by zero323** [comment]
In general I am fine with that, but when it comes to merging I always prefer to get another opinion from one of the remaining team members :)

**Comment by eliasah** [comment]
LGTM I was thinking about this last week as well.
