### ISSUE TITLE
Split README into Scala / PySpark / R

### ISSUE THREAD

**Issue by MrPowers** [awesome-spark/awesome-spark#200]
The Scala & PySpark library ecosystems and userbases have diverged enough to consider splitting up the README.

Scala users might consider [spark-daria](https://github.com/MrPowers/spark-daria) & [deequ](https://github.com/awslabs/deequ).

PySpark users should focus on the mirror libraries [quinn](https://github.com/MrPowers/quinn/) and [python-deequ](https://github.com/awslabs/python-deequ).

The current setup of the README is best for the language polyglots, but think most users are only interested in one API.  I'd be happy to take a stab splitting this up if folks think it'd be a good idea.

**Comment by zero323** [comment]
I am a bit skeptical about this. While there exist libraries targeted for specific languages, there are not that common (and often not well maintained).  Many projects that we include here are one way or either language agnostic  (i.e. data sources) or provide bindings for at least Scala and Python. 

There is also a problem with 3rd party language bindings.

At some point I considered adding some indicator (visual for GitHub, tagging to support filtering), but I seemed like an overkill, given relatively small number of actively maintained projects.

**Comment by MrPowers** [comment]
Cool, happy to keep the organization as-is.  This project adds a lot of value either way.  Thanks for responding!
