### ISSUE TITLE
Broken link to Spark Technology Center 

### ISSUE THREAD

**Issue by wdavidw** [awesome-spark/awesome-spark#209]
The current link redirects `http://spark.tc/blog/` redirect to ibm home page.

**Comment by eliasah** [comment]
Unfortunately, it seems like IBM has removed the Blog for some reason

**Comment by zero323** [comment]
Spark Technology Center changed to CODAIT (Center for Open source, Data and AI Technology) if I am not mistaken.

@BryanCutler, could you chip in here, please? TIA.

**Comment by wdavidw** [comment]
I don't see much articles around Spark on the [CODAIT section](https://www.ibm.com/opensource/centers/codait/) but their projects and trusted AI pages are interested. Also, on [Adaltas blog](https://www.adaltas.com/en/articles/), we regularly post Spark related articles if you are interested. There is tag dedidicated to [spark](https://www.adaltas.com/en/tag/apache-spark/).

**Comment by BryanCutler** [comment]
Thanks for checking on this, but yeah, after the transition to CODAIT I do not know of any Spark specific content.
