### ISSUE TITLE
Add description to Lightning-Fast Big Data Analysis. Advanced Analytics with Spark.

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#28]

**Comment by eliasah** [comment]
Hello @sryza @srowen ! hope you are both doing ok. Would one of you care about writing a small description about your book for awesome-spark ? Thanks ! :)

**Comment by srowen** [comment]
If you just need a description, I think it's reasonable to use the text at http://shop.oreilly.com/product/0636920035091.do or https://smile.amazon.com/Advanced-Analytics-Spark-Patterns-Learning/dp/1491912766
