### ISSUE TITLE
Clean MOOCS section

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#29]
CS100 and   CS190 are no longer offered. The new curriculum contains five different courses. We also need proper descriptions.

**Comment by zero323** [comment]
@atalwalkar, @bmc As instructors, would you like to share some insights?

**Comment by eliasah** [comment]
They are not offered but they are archived. Wouldn't be better to just tag them ?

**Comment by zero323** [comment]
I am not sure. At the first glance these seem to be redundant when taking new versions into account.  Maybe split between active and archived is not a bad idea.

**Comment by eliasah** [comment]
:+1:
