### ISSUE TITLE
Version and language labeling

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#41]
Should we provide an optional version or language specific labels? The former one can become a serious issue with upcoming 2.0+. The latter one is probably less useful and not worth the effort.

**Comment by eliasah** [comment]
I'm not sure what you mean by that.

**Comment by zero323** [comment]
I mean roughly something like this https://github.com/awesome-spark/awesome-spark/tree/badges

Of course not this particular style.

**Comment by eliasah** [comment]
But if we start doing this. The page won't be readable anymore

**Comment by eliasah** [comment]
I suggest rather to make a matrix on a different page.

**Comment by zero323** [comment]
Well, there are different variants out there which can be used to provide additional info. [Awesome Scala](https://github.com/lauris/awesome-scala) tracks for example stars and forks. But lets close it for now and revisit if we have an actual project.
