### ISSUE TITLE
Inconsistent captialization of the descriptions.

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#44]
Right now have three different conventions:

- [link] - lowercase foo bar. 
- [link] - Uppercase foo bar.
- [link] -  Uppercase Foo Bar.

We should choose one (the second approach is probably canonical given we use full sentences for descriptions) and adjust the rest.

**Comment by eliasah** [comment]
I'd rather we stay with [link] - Uppercase foo bar and.

**Comment by zero323** [comment]
Fine by me.

**Comment by zero323** [comment]
@eliasah Is it acceptable now?
