### ISSUE TITLE
Non-active repositories

### ISSUE THREAD

**Issue by eliasah** [awesome-spark/awesome-spark#47]
What should we do about inactive repositories ? example : [https://github.com/irvingc/dbscan-on-spark](https://github.com/irvingc/dbscan-on-spark)

**Comment by zero323** [comment]
Do these still compile for 1.6? If yes I would keep them as it is. There are many inactive projects around Spark, but many of these have simply no potential to be active. 2.0 can break a lot of stuff though.

**Comment by eliasah** [comment]
I can check. Maybe i can bump it to 1.6 if it's not to long on the worst case a submit a PR

**Comment by eliasah** [comment]
I've submitted a PR for that project [here](https://github.com/irvingc/dbscan-on-spark/pull/4) updating to spark 1.6.1

**Comment by eliasah** [comment]
I'll wait for my PR to be accepted. I'm not sure it's still maintained thought. Not sure what to do

**Comment by eliasah** [comment]
we still haven't decided what do we do about non-maintained repos. I mean I won't be doing what I did for the other like with DBSCAN

**Comment by zero323** [comment]
I would reconsider this when 2.0.0 is out. If project still compiles and passes test then keep it even it hasn't been active. If it doesn't, drop it.

By project:

- https://github.com/harsha2010/magellan/issues/56 -  seems like there is a hope
- neo4j-mazerunner - inactive but actively presented on Meetups
- https://github.com/alitouka/spark_dbscan - probably abandoned

**Comment by zero323** [comment]
One possible idea is to create a separate file for interesting but abandoned projects.

**Comment by eliasah** [comment]
Thus I'm closing this issue for now.
