### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#62]
I've been thinking about adding a list of useful Spark Docker images. This it not very long but I think it can be useful. It could go the resources section.

## Resources

... 

### Blogs

....
### Docker images:

- [jupyter/docker-stacks/pyspark-notebook/](https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook) - PySpark with Jupyter Notebook and Mesos client.
- [Spark Notebook Generator](http://spark-notebook.io/) - Package generator for Spark notebook supporting multiple formats, including Docker images.
- [sequenceiq/docker-spark](https://github.com/sequenceiq/docker-spark) - Spark on  Yarn images.
- [zero323/spark-in-a-box](https://github.com/zero323/spark-in-a-box/commits?author=zero323) - Awesome Docker images generator.

**Comment by eliasah** [comment]
That would be great ! I'm having troubles finding stables one thought
