### ISSUE TITLE
Does it make sense to include sparkinabox

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#69]
@eliasah What do you think? It is not particularly mature and I am cautious when it comes to self-promotion...

**Comment by eliasah** [comment]
I think that it a legitimate tool. Maybe some more documentation and we can add it.

**Comment by eliasah** [comment]
I think that at one point, we should add sparkinabox, but maybe setting a milestone to it first so it can get included here.

**Comment by zero323** [comment]
OK, I'll think about it. I consider rewriting it using https://github.com/ansible/ansible-container but I am not sure.
