### ISSUE TITLE
sparkapi and sparklyr

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#74]
- should we include these two or wait and see how things go?
- if we include where should these go? Should we add these separately?

@eliasah

**Comment by eliasah** [comment]
I'd rather that we wait. I'm not very certain about them.

**Comment by zero323** [comment]
Well, these have much stronger support than quite a few projects on the list.

**Comment by eliasah** [comment]
if so, we should add them.

**Comment by zero323** [comment]
SparkAPI has been dropped so part of the problem resolved itself :)

**Comment by zero323** [comment]
@eliasah Just a friendly reminder that you committed to handle this :)

**Comment by eliasah** [comment]
LGTM, I'll work on it. :)

**Comment by zero323** [comment]
@eliasah ping :)

**Comment by eliasah** [comment]
Yes I saw it. :)

**Comment by zero323** [comment]
@eliasah Friendly reminder :)
