### ISSUE TITLE
Contribution guidelines 

### ISSUE THREAD

**Issue by zero323** [awesome-spark/awesome-spark#8]
We need a clear contribution guidelines.

**Comment by eliasah** [comment]
I totally agree with that. Do you have suggestions ?

**Comment by zero323** [comment]
Python version looks reasonable enough: https://github.com/vinta/awesome-python/blob/master/CONTRIBUTING.md

**Comment by eliasah** [comment]
Exactly, this is somehow what I am doing !

**Comment by eliasah** [comment]
Should we close this issue now that we have written the contribution guideline ?

**Comment by zero323** [comment]
If you merged related commit then sure. It still a work in progress though.
