### ISSUE TITLE
More language bindings

### ISSUE THREAD

**Issue by nchammas** [awesome-spark/awesome-spark#97]
I can't vouch for the quality or maturity of these bindings, but you may want to consider them.

* Haskell: https://github.com/tweag/sparkle
* Node.js:
  * https://github.com/EclairJS/eclairjs-node
  * https://github.com/henridf/apache-spark-node

**Comment by eliasah** [comment]
I won't be able to judge for that neither but I suggest to make two separate PR, one for each language binding. Can you please do that @nchammas by following the [contribution guideline](https://github.com/awesome-spark/awesome-spark/blob/master/contributing.md)?

**Comment by zero323** [comment]
Funny enough I thought about `sparkle` the other day but my Haskel is way to rudimentary to devote my time to testing it. Maybe @alpmestan or @mboes  drop by and convince us that it should be here.

It looks like `apache-spark-node` is one-off attempt and is no longer developed. The [main EclairJS](https://github.com/EclairJS/eclairjs) looks relatively active so maybe we should consider it. If you want to advocate for it @nchammas I am opened to the idea but I am not willing to test it myself. `libuv` is the closest I get to this stuff these days :-)

**Comment by nchammas** [comment]
Hmm, this was more of a suggestion in passing, just in case y'all hadn't heard of these projects. I'm not interested in advocating for any of these projects, so feel free to wait for one of the people you pinged to chime in or feel free to just close this issue. 👍

**Comment by zero323** [comment]
Thanks @nchammas Let's wait for some users interested in evangelism then.

**Comment by alpmestan** [comment]
The Haskell bindings (_sparkle_) are still actively being worked on, used by a couple of companies but nowhere near complete in terms of API coverage. I can only speak for myself (@mboes' opinion might be different) but I think it would make sense to include it in your list regardless, as we have a pretty decent story for RDD and dataframe related functionality and it's pretty easy for people to add bindings to new classes/methods when they need it, usually contributing them upstream. If more people know about it and use it (by e.g finding out about it in your list), the API coverage and the robustness will certainly increase. I however would not mind it if you want to wait a bit before including it.

**Comment by zero323** [comment]
Thanks @alpmestan Let's open a separate issue and / or PR to track this. Does it sound OK?
